homework 1 - manual
GIS-sys/MIPT_24_Android pull request #1
Opened 2024-02-26 17:50 UTC by GIS-sys

2024-03-10 13:58 UTC, Ksalim01 requested changes

2024-03-10 13:58 UTC, Ksalim01 commented on hw_kotlin/manual/main.kt
> +    //   such structures as TreeMap will not be faster
Почему? Получить такой список в дереве это O(m + logn), где m - длина ответа. У тебя получается всегда O(n)

2024-03-10 13:58 UTC, Ksalim01 commented on hw_kotlin/manual/main.kt
> +            this.addAnimal(it)
this можно не писать

2024-03-10 13:58 UTC, Ksalim01 commented on hw_kotlin/manual/main.kt
> +        this.idToAnimal.put(animal.id, animal)
В описании есть такое `У каждого животного есть ровно один  надзиратель`. Думаю можно как-нибудь сразу назначить кого-нибудь в качестве надзирателя для нового животного

2024-03-10 13:58 UTC, Ksalim01 commented on hw_kotlin/manual/main.kt
> +        }
Тут спорно, но я думаю, что в зоопарке можно переназчать надзирателей

2024-03-10 13:58 UTC, Ksalim01 commented on hw_kotlin/manual/main.kt
> +        return idToAnimal.getValue(id)
А если животного с таким айди нет?

2024-03-10 13:58 UTC, Ksalim01 commented on hw_kotlin/manual/main.kt
> +    }
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/filter-is-instance.html

2024-03-10 15:20 UTC, GIS-sys commented on hw_kotlin/manual/main.kt
> +    }
Эта функция делает ровно то же, что я написал сам - не понимаю, в чём смысл переписывать эту функцию через неё? Получится ведь как-то так:
```kotlin
    inline fun <reified T: Animal> getAllAnimalsOfType(): List<Animal> {
        return this.idToAnimal.values.filterIsInstance<T>()
    }
```
что не сильно проще

2024-03-10 16:19 UTC, GIS-sys commented on hw_kotlin/manual/main.kt
> +    //   such structures as TreeMap will not be faster
Асимптотика мтожидания всё равно O(n); и я не уверен, что константа в дереве настолько маленькая, что обычный список не будет быстрее. Но на всякий случай заменю на TreeMap, пусть даже и просто для тренировки

2024-03-10 16:40 UTC, GIS-sys commented on hw_kotlin/manual/main.kt
> +        return idToAnimal.getValue(id)
Теперь кидаем исключение

2024-03-14 11:19 UTC, Ksalim01 commented on hw_kotlin/manual/main.kt
> +        return idToAnimal.getValue(id)
Вообще лучше избегать проброс исключений. Лучший вариант возвращать null

2024-03-14 11:39 UTC, GIS-sys commented on hw_kotlin/manual/main.kt
> +        return idToAnimal.getValue(id)
Переписал на null

2024-03-15 08:55 UTC, Ksalim01 approved these changes

2024-03-15 08:55 UTC, merged