homework 1 - yandex contest 5
GIS-sys/MIPT_24_Android pull request #6
Opened 2024-02-26 17:52 UTC by GIS-sys

2024-02-27 09:41 UTC, Ksalim01 requested changes

2024-02-27 09:41 UTC, Ksalim01 commented on hw_kotlin/yc5/main.kt
> +    var listMax: MutableList<Long> = mutableListOf()
1. Нужно заменить на private val. var использовать ни к чему, т.к. если объект под ссылкой мутабельный, то над ним можно проводить модифицирующие операции даже если сама ссылка на объект немутабельна
2. Лучше завести один список пар (значение, максимум). И сразу скажу, лучше завести отдельный приватный data class  с этими двумя полями.

2024-02-27 09:41 UTC, Ksalim01 commented on hw_kotlin/yc5/main.kt
> +        File("input.txt").forEachLine {
Это явно не то решение, которое было в контесте

2024-02-27 10:08 UTC, GIS-sys commented on hw_kotlin/yc5/main.kt
> +        File("input.txt").forEachLine {
Почему не то?..
Если вопрос про использование файлов - тут нужно считывать огромное количество данных с stdin. Поэтому, по стандартным законам олимпиадного программирования, я заменил на файловый ввод-вывод

2024-03-02 18:59 UTC, Ksalim01 approved these changes

2024-03-02 18:59 UTC, Ksalim01 commented on hw_kotlin/yc5/main.kt
> +data class ValueWithMax(val value: Long, val max: Long)
just Node

2024-03-02 18:59 UTC, merged